import type { Metadata } from "next";
import {Exo, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner"
import WrapperCom from "./_Components/WrapperCom/WrapperCom";
import Footer from "./_Components/Footer/Footer";
import TanStackProvider from "@/Providers/TanStackProvider";


const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={exo.className}
      >
          <TanStackProvider>
          <WrapperCom>
          <Navbar></Navbar>
        </WrapperCom>
        {children}
        <Toaster></Toaster>
        <Footer></Footer>
        </TanStackProvider>
        
      </body>
    </html>
  );
}
